platform :ios, '9.0'
inhibit_all_warnings!


target 'ThinkSharer' do
    
    pod 'AFNetworking', '~> 3.1.0'
    pod 'SDWebImage', '~> 4.0.0'
    pod 'MJRefresh'
    pod 'Realm'
    pod 'MBProgressHUD'
    pod 'AMap3DMap-NO-IDFA'
    pod 'AMapLocation-NO-IDFA'
    pod 'Masonry'
#    pod 'CTAssetsPickerController',  '~> 3.3.1'
    pod 'PYPhotoBrowser'
    pod 'PureLayout', '~> 3.0.2'




end

